### ISSUE TITLE
Once the number of items in the CustomSuggestionAdapter decreases, the list view shrinks.

### ISSUE THREAD

**Issue by c4adarsh** [mancj/MaterialSearchBar#24]
Once the number of items in the CustomSuggestionAdapter decreases, the list view shrinks.
Even if i add the items into the list agiain. It never increases.

Steps to reproduce : 
1. Try to initialize the CustomSuggestionAdapter with zero items.
2. Now increase the number of items in the CustomSuggestionAdapter during runtime.
3. We can never see the list view of suggestions coming up.

I was trying to do a predictive search by calling a webservice. The number of items increases and decreases based on the search key. 

"I have done some workaround to fix the issue for me for now", but its a temporary fix.

My further steps would be to combine recent searches when user hasn't typed anything, and once the user starts typing i will call the webservice and get the results and show in this suggestions area. i will write an article on the Material Search bar once I complete my implementation.

Thanks,
Adarsh

**Comment by mancj** [comment]
I fixed this bug, try the latest version. Let me know if the error was and I'll make a new release.
```groovy
compile 'com.github.mancj:MaterialSearchBar:0.6'
```

**Comment by mancj** [comment]
The problem was that the maxSuggestionsCount default value in the SuggestionsAdapter is equals 0.

**Comment by c4adarsh** [comment]
Its not working. See the below method. I have used the setMaxSuggestionCount. Should I do something else.

private void openSearchArea(List<String> suggestions){
            searchBar.setMaxSuggestionCount(suggestions.size());
            customSuggestionsAdapter.setSuggestions(suggestions);
            customSuggestionsAdapter.notifyDataSetChanged();
    }

**Comment by mancj** [comment]
sorry, I made a mistake in the commentary. You need to compile the version 0.6.1-beta. I updated my comment above

**Comment by c4adarsh** [comment]
customSuggestionsAdapter.setMaxSuggestionsCount(suggestions.size());
customSuggestionsAdapter.setSuggestions(suggestions);
customSuggestionsAdapter.notifyDataSetChanged();

still doesn't work

**Comment by mancj** [comment]
Post your adapter code, please.

**Comment by c4adarsh** [comment]
package com.zapoos.ilovezapoos.presentation.ui.adapters;

import android.graphics.Color;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.mancj.materialsearchbar.adapter.SuggestionsAdapter;
import com.zapoos.ilovezapoos.R;
import com.zapoos.ilovezapoos.util.Constants;

public class CustomSuggestionsAdapter extends SuggestionsAdapter<String, CustomSuggestionsAdapter.SuggestionHolder> {

    private SuggestionsAdapter.OnItemViewClickListener listener;

    private String mUnderline = Constants.WHITE;

    public CustomSuggestionsAdapter(LayoutInflater inflater) {
        super(inflater);
    }

    public void setListener(SuggestionsAdapter.OnItemViewClickListener listener) {
        this.listener = listener;
    }

    public void setUnderlineColor(String mColor){
        mUnderline = mColor;
    }

    @Override
    public void onBindSuggestionHolder(String suggestion, SuggestionHolder holder, int position) {
        holder.title.setText(suggestion);
        if(mUnderline == Constants.WHITE){
            holder.view.setBackgroundColor(Color.WHITE);
        }else{
            holder.view.setBackgroundColor(Color.WHITE);
        }
    }

    @Override
    public SuggestionHolder  onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = getLayoutInflater().inflate(R.layout.suggestion_row, parent, false);
        return new SuggestionHolder(view);
    }

    @Override
    public int getSingleViewHeight() {
        return 60;
    }

    class SuggestionHolder extends RecyclerView.ViewHolder{
        protected TextView title;
        protected View view;

        public SuggestionHolder(View itemView) {
            super(itemView);
            title = (TextView) itemView.findViewById(R.id.my_list_item);
            itemView.setOnClickListener(new View.OnClickListener(){
                @Override
                public void onClick(View v) {
                   listener.OnItemClickListener(getAdapterPosition(),v);
                }
            } );
            view = (View) itemView.findViewById(R.id.view);
        }
    }
}

**Comment by mancj** [comment]
I don't see any problems. Can you show the xml file?

**Comment by c4adarsh** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="50dp"
    android:clickable="true"
    android:background="?attr/selectableItemBackground"
    android:gravity="center_vertical"
    android:orientation="vertical">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/my_list_item"
        android:layout_gravity="start"
        android:gravity="center_vertical"
        android:textColor="@android:color/black" />
    <View
        android:id="@+id/view"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:layout_gravity="bottom"
        android:background="#000000" />
</LinearLayout>

**Comment by mancj** [comment]
I meant the xml file where you create MaterialSearchBar, not the adapter's row.

**Comment by c4adarsh** [comment]
[serach_layout.txt](https://github.com/mancj/MaterialSearchBar/files/762246/serach_layout.txt)

**Comment by mancj** [comment]
It still doesn't work with height `wrap_content`?

**Comment by c4adarsh** [comment]
Nop. It doesn't work. Leave this issue open. I will check your code after 10th. Thanks for the help.
